hinosxz/chowchow

.travis.yml, Dockerfile, scripts/merge-prod-to-staging.sh
I added the Git Hub token in the URL of the push command.
Please try to push master and check that it is merged to staging. Try with another branch and check that it is not merged. 
Check that the CI is launched and the logs of "after success" on Travis
=> Domitille : merge to staging automatically travis

.travis.yml, prod.Dockerfile, src/main/resources/application-dev.properties, src/main/resources/application-prod.properties, src/main/resources/application-staging.properties, src/main/resources/application.properties, staging.Dockerfile
- Fixes an issue where Heroku couldn't read the env variables
- Fixes port binding with Heroku
https://trello.com/c/1Dro7l8K
It's on staging!
Hit https://chowchow-staging.herokuapp.com/shows/1, you should get `Peaky Blinders`
=> 🔧 Fix broken app on Heroku

src/main/resources/application.properties
Removes duplicate `spring.datasource.url=` in application properties
🚑
Try packaging the app locally, it should work now
=> 🚑 Fix dev build

.gitignore, README.md, docker-compose.yml, src/main/java/com/centralesupelec/chowchow/lib/RestTemplateResponseErrorHandler.java, src/main/java/com/centralesupelec/chowchow/search/controllers/SearchController.java, src/main/java/com/centralesupelec/chowchow/search/controllers/TraktSearch.java, src/main/java/com/centralesupelec/chowchow/search/service/SearchService.java, src/main/java/com/centralesupelec/chowchow/search/web/SearchWebController.java, src/main/java/com/centralesupelec/chowchow/show/web/ShowsWebController.java
Opens a `/search` route to search for a show using Trakt API. Filtering is applied with the query parameter `name`. 
https://trello.com/c/7H3XU94k
Hit https://chowchow-staging.herokuapp.com/search?name=handmaid and you should be able to find `The Handmaid's Tale`
=> Add search route for shows

docker-compose.yml, setup_postgres_db.sql, src/main/java/com/centralesupelec/chowchow/lib/TraktAPI.java, src/main/java/com/centralesupelec/chowchow/show/controllers/ShowDTO.java, src/main/java/com/centralesupelec/chowchow/show/domain/ShowEntity.java, src/main/java/com/centralesupelec/chowchow/show/domain/ShowRepository.java, src/main/java/com/centralesupelec/chowchow/show/service/ShowsService.java, src/main/java/com/centralesupelec/chowchow/trakt/controllers/AlertController.java, src/main/java/com/centralesupelec/chowchow/trakt/controllers/SearchController.java, src/main/java/com/centralesupelec/chowchow/trakt/controllers/TraktEpisode.java, src/main/java/com/centralesupelec/chowchow/trakt/controllers/TraktSearch.java, src/main/java/com/centralesupelec/chowchow/trakt/service/AlertService.java, src/main/java/com/centralesupelec/chowchow/trakt/service/SearchService.java, src/main/java/com/centralesupelec/chowchow/trakt/web/AlertWebController.java, src/main/java/com/centralesupelec/chowchow/trakt/web/SearchWebController.java, src/main/resources/application-dev.properties
It adds an `/alerts` route that returns the episodes to be aired in the next 3 days for the shows I'm following.
*TODO: connect that with users, link each episode with its show id*
https://trello.com/c/yu0ht2o1
Hit https://chowchow-staging.herokuapp.com/alerts
3 shows are in the Database, Supergirl and The Flash that air on Mondays and Seal Team that airs on Thursdays. Knowing that you should get more or less episodes.
=> ✨ Add /alerts route

src/main/java/com/centralesupelec/chowchow/TMDB/controllers/SearchController.java, src/main/java/com/centralesupelec/chowchow/TMDB/web/AlertWebController.java, src/main/java/com/centralesupelec/chowchow/TMDB/web/SearchWebController.java
Adds a `/search/{id}` route to get details for a specific show
https://trello.com/c/lJ1m2qeD
Hit https://chowchow-staging.herokuapp.com/search/69478 and you should get details for `The Handmaid's Tale`
=> Add a show details route

pom.xml, src/main/java/com/centralesupelec/chowchow/ChowchowApplication.java, src/main/java/com/centralesupelec/chowchow/TMDB/controllers/AlertController.java, src/main/java/com/centralesupelec/chowchow/TMDB/controllers/SearchController.java, src/main/java/com/centralesupelec/chowchow/TMDB/controllers/TMDBEpisodeDTO.java, src/main/java/com/centralesupelec/chowchow/TMDB/controllers/TMDBSearchDTO.java, src/main/java/com/centralesupelec/chowchow/TMDB/controllers/TMDBSearchShowDTO.java, src/main/java/com/centralesupelec/chowchow/TMDB/controllers/TMDBShowDTO.java, src/main/java/com/centralesupelec/chowchow/TMDB/service/AlertService.java, src/main/java/com/centralesupelec/chowchow/TMDB/service/SearchService.java, src/main/java/com/centralesupelec/chowchow/TMDB/web/AlertWebController.java, src/main/java/com/centralesupelec/chowchow/TMDB/web/SearchWebController.java, src/main/java/com/centralesupelec/chowchow/lib/RestTemplateResponseErrorHandler.java, src/main/java/com/centralesupelec/chowchow/lib/TMDBAPI.java, src/main/java/com/centralesupelec/chowchow/show/controllers/ShowDTO.java, src/main/java/com/centralesupelec/chowchow/show/controllers/ShowsController.java, src/main/java/com/centralesupelec/chowchow/show/domain/ShowEntity.java, src/main/java/com/centralesupelec/chowchow/show/domain/ShowRepository.java, src/main/java/com/centralesupelec/chowchow/show/service/ShowsService.java, src/main/java/com/centralesupelec/chowchow/show/web/ShowsWebController.java, src/main/java/com/centralesupelec/chowchow/user/controllers/UserDTO.java, src/main/java/com/centralesupelec/chowchow/user/controllers/UsersController.java, src/main/java/com/centralesupelec/chowchow/user/domain/PremiumUserEntity.java, src/main/java/com/centralesupelec/chowchow/user/domain/SubscriptionType.java, src/main/java/com/centralesupelec/chowchow/user/domain/UserEntity.java, src/main/java/com/centralesupelec/chowchow/user/domain/UserRepository.java, src/main/java/com/centralesupelec/chowchow/user/service/UsersService.java, src/main/java/com/centralesupelec/chowchow/user/service/UsersServiceImpl.java, src/main/java/com/centralesupelec/chowchow/user/web/UsersWebController.java, src/test/java/com/centralesupelec/chowchow/ChowchowApplicationTests.java
Adds `Google Java Format` as a maven dependency that'll be triggered on every commit to automatically reformat code before committing.
https://trello.com/c/PEE8VFKz
Nothing should change, but it's on staging!
-   [ ] I have a plan to verify that these changes are working as expected after deploy
=> ➕ 🎨 Add Google Java Format

.travis.yml, src/main/resources/application.properties
Fixes the CI: every push on a branch with a PR set up triggered a deploy to prod and a merge to staging.
https://trello.com/c/TtqyvpdU
Check travis logs
=> 🐛 Prevent pull request triggered pipelines from deploying

README.md, pom.xml, src/main/java/com/centralesupelec/chowchow/config/SwaggerConfig.java
Adds Swagger to our app. `/swagger-ui.html` now returns a UI with all the available endpoints for our app.
https://trello.com/c/cEcPByFd
It's on staging! Hit https://chowchow-staging.herokuapp.com/swagger-ui.html
=> ➕ 📝 Add swagger

.travis.yml, README.md
Adds a front-end travis config that triggers deploys to staging/prod versions of the UI on Heroku.
https://trello.com/c/aTPefTtM
It's on staging! Hit https://chowchow-ui-staging.herokuapp.com/
-   [x] This code has automated tests
=> Set up front-end deployment

pom.xml, src/main/java/com/centralesupelec/chowchow/TMDB/web/AlertWebController.java, src/main/java/com/centralesupelec/chowchow/config/AppAuthProvider.java, src/main/java/com/centralesupelec/chowchow/config/SecurityConfig.java, src/main/java/com/centralesupelec/chowchow/user/controllers/AppAuthProvider.java, src/main/java/com/centralesupelec/chowchow/user/controllers/RegisterUserDTO.java, src/main/java/com/centralesupelec/chowchow/user/controllers/UsersController.java, src/main/java/com/centralesupelec/chowchow/user/domain/SubscriptionType.java, src/main/java/com/centralesupelec/chowchow/user/domain/UserEntity.java, src/main/java/com/centralesupelec/chowchow/user/domain/UserRepository.java, src/main/java/com/centralesupelec/chowchow/user/service/UsersService.java, src/main/java/com/centralesupelec/chowchow/user/web/AuthWebController.java, src/main/java/com/centralesupelec/chowchow/user/web/UsersWebController.java
It adds user HttpSession and basic authentication for the api.
https://trello.com/c/uutPGtGz
Everything is on staging. To test the new features you can register as a user then add some shows to your list and tadaaa
=> :sparkles: Add authentication and session to api

src/main/java/com/centralesupelec/chowchow/likes/controllers/LikesController.java, src/main/java/com/centralesupelec/chowchow/likes/domain/Mark.java, src/main/java/com/centralesupelec/chowchow/likes/web/LikesWebController.java, src/main/java/com/centralesupelec/chowchow/user/controllers/UsersController.java, src/main/java/com/centralesupelec/chowchow/user/web/UsersWebController.java
Encapsulate the `likes` logic into specific controllers.
Return int for the `Mark` enum
https://trello.com/c/2wjtg2TB/44-refactor-likes-routes
=> ♻️ Refactor likes encapsulation

src/main/java/com/centralesupelec/chowchow/TMDB/controllers/TMDBShowDTO.java, src/main/java/com/centralesupelec/chowchow/likes/controllers/LikeDTO.java, src/main/java/com/centralesupelec/chowchow/likes/controllers/LikesController.java, src/main/javascript/src/Routes.tsx, src/main/javascript/src/components/show-list/PageShowList/PageShowList.tsx, src/main/javascript/src/components/show-list/ShowItem/ShowItem.tsx, src/main/javascript/src/components/show-list/ShowItem/show-item.scss, src/main/javascript/src/components/ui/AppLayout/app-layout.scss, src/main/javascript/src/components/ui/Mark/Mark.tsx, src/main/javascript/src/components/ui/Mark/mark.scss, src/main/javascript/src/components/ui/Placeholder/Placeholder.tsx, src/main/javascript/src/components/ui/Placeholder/placeholder.scss, src/main/javascript/src/components/ui/ui-constants.scss, src/main/javascript/src/lib/hooks.ts, src/main/javascript/src/lib/types.ts
Adds a Show List page
https://trello.com/c/FemMokfW
It's on staging!
=> ✨ Show list page

src/main/java/com/centralesupelec/chowchow/TMDB/controllers/AlertController.java, src/main/java/com/centralesupelec/chowchow/likes/controllers/LikesController.java, src/main/java/com/centralesupelec/chowchow/likes/web/LikesWebController.java, src/main/javascript/src/components/home/Alerts/Alerts.tsx, src/main/javascript/src/components/home/PageHome/PageHome.tsx, src/main/javascript/src/components/home/ShowView/ShowView.tsx, src/main/javascript/src/components/home/ShowView/ShowViewContainer.tsx, src/main/javascript/src/components/home/ShowView/show-view.scss, src/main/javascript/src/components/show-list/PageShowList/PageShowList.tsx, src/main/javascript/src/lib/api/likes.ts, src/main/javascript/src/lib/hooks.ts
https://trello.com/c/5XyfMnEy
Hit https://chowchow-ui-staging.herokuapp.com/, login and search for a show
=> ✨ Add a Like button

src/main/javascript/src/components/authentication/LoginForm/LoginForm.tsx, src/main/javascript/src/components/authentication/LoginForm/login-form.scss, src/main/javascript/src/components/authentication/PageLogin/PageLogin.tsx, src/main/javascript/src/components/authentication/PageLogin/page-login.scss, src/main/javascript/src/components/authentication/PageLogout/PageLogout.tsx, src/main/javascript/src/components/authentication/RegistrationForm/RegistrationForm.tsx, src/main/javascript/src/lib/api/register.ts
https://trello.com/c/TlvCn3eA
Hit https://chowchow-ui-staging.herokuapp.com/login
=> 💄 Improve login/logout UI/UX

src/main/java/com/centralesupelec/chowchow/config/PasswordHashConfig.java, src/main/java/com/centralesupelec/chowchow/config/SecurityConfig.java, src/main/java/com/centralesupelec/chowchow/user/controllers/AppAuthProvider.java, src/main/java/com/centralesupelec/chowchow/user/controllers/UsersController.java
https://trello.com/c/GdbjN8tK/54-hash-passwords
Go to [staging](https://chowchow-ui-staging.herokuapp.com/) log in.
=> 🔒 Add hashing to passwords

src/main/javascript/src/components/home/PageHome/PageHome.tsx
Simplest PR ever
-   [ ] I have a plan to verify that these changes are working as expected after deploy
=> Inline change to make app friendlier

src/main/javascript/src/components/show/PageShow/PageShow.tsx, src/main/javascript/src/components/show/SeasonList/SeasonList.tsx, src/main/javascript/src/components/show/ShowPanel/ShowPanel.tsx, src/main/javascript/src/lib/types.ts
Adds season details in the show panel, fetching data on click
https://trello.com/c/aTCmuOyU
Hit https://chowchow-ui-staging.herokuapp.com, go to your shows and open the panel.
=> ✨ Add season details

README.md, src/main/java/com/centralesupelec/chowchow/TMDB/controllers/AlertController.java, src/main/java/com/centralesupelec/chowchow/TMDB/controllers/SearchController.java, src/main/java/com/centralesupelec/chowchow/TMDB/service/AlertService.java, src/main/java/com/centralesupelec/chowchow/TMDB/service/AlertServiceImpl.java, src/main/java/com/centralesupelec/chowchow/TMDB/service/SearchService.java, src/main/java/com/centralesupelec/chowchow/TMDB/service/SearchServiceImpl.java, src/main/java/com/centralesupelec/chowchow/config/SecurityConfig.java, src/main/java/com/centralesupelec/chowchow/likes/controllers/LikesController.java, src/main/java/com/centralesupelec/chowchow/user/controllers/UsersController.java, src/main/java/com/centralesupelec/chowchow/user/service/UserService.java, src/main/java/com/centralesupelec/chowchow/user/service/UserServiceImpl.java
It adds the interfaces to contract the services and loooots of doc.
https://trello.com/c/8htvy8yY/60-add-interfaces-to-all-services
=> 🎨 ✏ Add interfaces to contract services

README.md, docker-compose.yml, src/main/javascript/.dockerignore, src/main/javascript/Dockerfile, src/main/javascript/package.json
- Dockerizes the front-end app to simplify the whole dev setup. 
- Wraps up a complete readme
- Rearranges npm dependencies between dev and non-dev
https://trello.com/c/Hl6dlf15
Pull the branch and try `docker-compose up --build`.
Should not change anything to staging and prod.
=> 🐳 Dockerize the front-end

src/main/java/com/centralesupelec/chowchow/lib/RestTemplateResponseErrorHandler.java
Fixes a bad error type returned by the error handler
🐛
-   [ ] I have a plan to verify that these changes are working as expected after deploy
=> 🐛 Fix error type

src/main/java/com/centralesupelec/chowchow/TMDB/service/SearchServiceImpl.java, src/main/java/com/centralesupelec/chowchow/lib/TMDBAPI.java
See title
https://trello.com/c/abE7eDgV
-   [ ] I have a plan to verify that these changes are working as expected after deploy
=> 💡 Add code comments for TMDB API
